### ISSUE TITLE
Implement routes that go outside the school

### ISSUE THREAD

**Issue by bholmbertelsen** [WalnutProgramming/Directions#14]
The fastest way to get from 1101 to 3726 is outside

**Comment by Aurelius333** [comment]
This is something we might want to do eventually, but it’s not a priority.

**Comment by Aurelius333** [comment]
The other hard part about this is that if there's bad weather or something, people might not want to go outside. We could add an option for allowing outside routes, but that's not something we should worry about right now. We're trying to give people a route that works, not necessarily the fastest route. But thanks for the suggestion.
