### ISSUE TITLE
Add information about joining Programming Club

### ISSUE THREAD

**Issue by Aurelius333** [WalnutProgramming/Directions#174]
In #173, I removed the part about how to join the club:

> The Walnut Hills Programming Club, a chapter of INTERalliance ~~, meets every Thursday at 4:00 PM using the Google Meet code "WHProgrammingClub" (accessible only through CPS accounts). The club~~ is open to everyone interested in computers and IT who want...

This file should be updated once you know the room and meeting days: <https://github.com/WalnutProgramming/Directions/blob/master/src/views/AboutPage.vue#L48>.

@regexBuster @lizavolo

**Comment by regexBuster** [comment]
I've added that we meet 3 to 4 in 3104 on Thursdays.
