### ISSUE TITLE
Suggest on main page that iOS users install as an app

### ISSUE THREAD

**Issue by Aurelius333** [WalnutProgramming/Directions#2]
On Android devices, there should already be a button at the top of the page that says "Install as App". This doesn't appear on iPhones because iOS doesn't support install buttons for Progressive Web Apps. 

So for iPhone users, we might want to add instructions on the bottom of the page (the file`index.html`) on how to install the app. For example: 
> To install this page as an app, press <img width="22" alt="image" src="https://user-images.githubusercontent.com/22969541/66788688-8a1b1500-eeb6-11e9-9525-3e653b9275fd.png"> at the bottom of the page and then press "Add to Home Screen".

**Comment by Buster422** [comment]
I've got this finished I gotta get home and change the repository though. I'll update this when I do so.

**Comment by Buster422** [comment]
Sent a pull request which should add a new div in the index.html with the needed text and image call. It should also contain some style.css changes for paragraphs and the image for ios users.
