### ISSUE TITLE
Text in Minus Buttons Isn't Centered in iOS

### ISSUE THREAD

**Issue by presssssure** [WalnutProgramming/Directions#42]
They looks like this on Windows:
![image](https://user-images.githubusercontent.com/33643911/71450117-5582cf80-2729-11ea-895e-0fe862e735c2.png)
And this on iOS:
![image](https://user-images.githubusercontent.com/33643911/71450128-7814e880-2729-11ea-8951-ea19db55611b.png)

**Comment by presssssure** [comment]
fixed

**Comment by Aurelius333** [comment]
fixed by #45
