### ISSUE TITLE
Hover on Minus Buttons and Plus Button Doesn't End on iOS

### ISSUE THREAD

**Issue by presssssure** [WalnutProgramming/Directions#43]
After the user touches the minus button or plus button it stays as if a mouse was hovered over it until the user touches another place on the screen.
![image](https://user-images.githubusercontent.com/33643911/71450149-fb363e80-2729-11ea-8326-0bc8bfdb9ebf.png)
This could possibly be fixed by triggering something with the buttons on touchended.

**Comment by Aurelius333** [comment]
@presssssure  I can fix this by using the mouseover and mouseleave events to toggle a CSS class (based on whether the mouse is over it), but that would mean the hover effect wouldn't happen at all on touch devices.
