### ISSUE TITLE
Little corner in the Music Lyceum has incorrect directions leading to it

### ISSUE THREAD

**Issue by presssssure** [WalnutProgramming/Directions#47]
This issue occurs because the hallway has a fork and a turn in the same spot, so depending on which way a person is coming from the fork either needs to be FRONT or RIGHT, but it's only labelled as RIGHT in the code.
![image](https://user-images.githubusercontent.com/33643911/71549648-cecf2c00-298e-11ea-99fd-13f33480ea09.png)
Blue is the way it should take the user, purple is the way it appears to take the user.
![image](https://user-images.githubusercontent.com/33643911/71549644-c4149700-298e-11ea-9a27-e39a31073aad.png)
We could probably remedy this by making the blue and purple hallways separate so there is no turn when 2 sections are being joined, only a fork.
![image](https://user-images.githubusercontent.com/33643911/71549674-75b3c800-298f-11ea-88ab-5ba9b2a6614b.png)

**Comment by Aurelius333** [comment]
That sounds like a good idea. If we do that, it will introduce some more confusing wording when turning into that corner, but if I make some changes to room-finder, it should work well. 

(I’ve been trying to figure out how to make the transitions between hallways sound more natural in room-finder, and I think I might have figured it out. It might be a few days, though.)
