### ISSUE TITLE
Allow a room to have aliases

### ISSUE THREAD

**Issue by Aurelius333** [WalnutProgramming/Directions#7]
For example, people should be able to say they want to go to the "senior high gym", "language lab", "main office", "spirit shop", etc., but they should also be able to refer to them by their room numbers. This will probably involve adding a field to the `Room` class in `hallwayDefinition.js` called `aliases`, which is an array of strings. `aliases` will only be used when the user is typing in a room name, and *not* when we're making directions.

**Comment by bholmbertelsen** [comment]
#18
