### ISSUE TITLE
Add the 1500s, 2500s, and 3500s

### ISSUE THREAD

**Issue by Aurelius333** [WalnutProgramming/Directions#9]
This is the confusing section behind the auditorium

**Comment by presssssure** [comment]
behind auditorium:
2502 2510
2502 2505
2502 (stage) 2505 (scene shop)
  2503 (theater)

     3505
     3504
          3503
    storage

blackbox high rise

**Comment by Aurelius333** [comment]
@presssssure and anyone else who's familiar with the performing arts center

### Things we need to figure out

Is 2502 the room number for the stage? I don't see it on the map. Right now, we don't have a way to have multiple entrances for the same room, so maybe we should just include one entrance, or maybe we should make multiple rooms for it so that people can choose which entrance to go through. 

Also, it looks like rooms 2508 and 2509 are inside of 2505? What are those rooms? Do we need them?

What's going on with 3508, 3507, and 3506? Are those classrooms people need to get to?

Are there actual classrooms on the first floor (1500s)? I didn't even realize it existed until a few days ago.

### Maps for reference
#### 2500s
<img width="743" alt="image" src="https://user-images.githubusercontent.com/22969541/68086874-31d49480-fe1e-11e9-8530-381d773757e3.png">

#### 3500s
<img width="788" alt="image" src="https://user-images.githubusercontent.com/22969541/68086929-d525a980-fe1e-11e9-8240-7a1c2fcab695.png">

#### 1500s
<img width="788" alt="image" src="https://user-images.githubusercontent.com/22969541/68086956-20d85300-fe1f-11e9-873c-96846763243b.png">

**Comment by Aurelius333** [comment]
I added most of the 2500s and 3500s, and I'm not sure whether we need to add more. It would be helpful if someone who knows their way around there could look at 8abd9cd0c19ea7fdf614eeaff9275613b2bbfe88 and/or try it out.

**Comment by Aurelius333** [comment]
I’m just going to assume that all of these rooms are storage and that we don’t need to add them: 

- All of the 1500s
- 3508, 3507, 3506
- 2508, 2509

If anyone thinks we need to add any of those, please tell me or make a comment.

**Comment by Aurelius333** [comment]
TODO: check that 3502 exists
